version: "3"
services:

  traefik:
    image: traefik:alpine
    labels:
      - traefik.frontend.rule=Host:traefik.wbitt.com
      - traefik.port=8080
      - traefik.enable=true
    environment:
      AWS_ACCESS_KEY_ID: 'AKIAJKJGHLH43A2Q'
      AWS_SECRET_ACCESS_KEY: 'uC2QCpf.JNBUGLLUG4L4693Hltm0HZchbb83'
      AWS_DEFAULT_REGION: 'eu-central-1'
      AWS_HOSTED_ZONE_ID: 'Z1SVJKHGYUQ8L7'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml
      - ${PWD}/acme.json:/acme.json
      # note: acme.json need to have 0600 permissions.
    ports:
      - 80:80
      - 443:443
      - 8080:8080 

  nginx:
    image: nginx:alpine
    labels:
      - traefik.frontend.rule=Host:nginx.wbitt.com
      - traefik.port=80
      - traefik.enable=true
    volumes:
      - ${PWD}/example.com-index.html:/usr/share/nginx/html/index.html

  tomcat:
    image: tomcat:alpine
    labels:
      - traefik.frontend.rule=Host:tomcat.wbitt.com
      - traefik.port=8080
      - traefik.enable=true
    volumes:
      - ${PWD}/sample.war:/usr/share/tomcat/webapps/sample.war

  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD="SuperSecretPassword"
